version: '3.8'

services:
  user-service:
    build:
      context: ./userService
    image: taskin/user
    restart: 'no'
    ports:
      - 8080:50051
    links:
      - mongo

  mongo:
    image: mongo
    restart: 'no'
    environment:
      MONGO_INITDB_DATABASE: taskin-user
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  postgresdb:
  mysqldb:
  mongodb:
  mongodb_config:
